language: cpp

compiler:
  - gcc
  - clang

# Travis CI has 1.5 cores per VM, take advantage of it
# But first, the makefiles have to be fixed: all plugins are using the same .o's
env:
  - CONFIG="coverage debug" MAKEFLAGSPARALLEL="-j 2"

# requires boost >= 1.49 to compile in C++11 mode
# see http://stackoverflow.com/questions/11302758/error-while-copy-constructing-boostshared-ptr-using-c11
# we use the irie/boost ppa for that purpose

# we get libyaml-cpp-dev from kubuntu backports

before_install:
  - git submodule update --init --recursive
#  - sudo add-apt-repository -y ppa:jon-severinsson/ffmpeg 
#  - sudo add-apt-repository -y ppa:irie/boost
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update

# Settings to try
env:
  - PKG_CONFIG_PATH=/opt/ocio/lib/pkgconfig

install:
# OpenColorIO
  - sudo apt-get install cmake libtinyxml-dev liblcms2-dev libyaml-cpp-dev libboost-dev
  - wget https://github.com/imageworks/OpenColorIO/archive/v1.0.9.tar.gz -O /tmp/ocio-1.0.9.tar.gz
  - tar zxf /tmp/ocio-1.0.9.tar.gz > /dev/null 2>&1
  - cd OpenColorIO-1.0.9
  - mkdir _build
  - cd _build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/opt/ocio -DCMAKE_BUILD_TYPE=Release -DOCIO_BUILD_JNIGLUE=OFF -DOCIO_BUILD_NUKE=OFF -DOCIO_BUILD_SHARED=ON -DOCIO_BUILD_STATIC=OFF -DOCIO_STATIC_JNIGLUE=OFF -DOCIO_BUILD_TRUELIGHT=OFF -DUSE_EXTERNAL_LCMS=ON -DUSE_EXTERNAL_TINYXML=ON -DUSE_EXTERNAL_YAML=ON -DOCIO_BUILD_APPS=OFF -DOCIO_USE_BOOST_PTR=ON -DOCIO_BUILD_TESTS=OFF -DOCIO_BUILD_PYGLUE=OFF
  - make $MAKEFLAGSPARALLEL && sudo make install
  - cd ../..
# OpenEXR
  - sudo apt-get install libopenexr-dev libilmbase-dev
# OpenImageIO (for some reason, freetype is not recognized)
  - sudo apt-get install libopenjpeg-dev libtiff-dev libjpeg-dev libpng-dev libboost-filesystem-dev libboost-regex-dev libboost-thread-dev libboost-system-dev libwebp-dev libfreetype6-dev libssl-dev
  - wget https://github.com/OpenImageIO/oiio/archive/Release-1.4.16.tar.gz -O /tmp/OpenImageIO-1.4.16.tar.gz
  - tar zxf /tmp/OpenImageIO-1.4.16.tar.gz > /dev/null 2>&1
  - cd oiio-Release-1.4.16
  - make $MAKEFLAGSPARALLEL USE_QT=0 USE_TBB=0 USE_PYTHON=0 USE_FIELD3D=0 USE_OPENJPEG=1 USE_OCIO=1 OIIO_BUILD_TESTS=0 OIIO_BUILD_TOOLS=0 OCIO_HOME=/opt/ocio INSTALLDIR=/opt/oiio dist_dir=. cmake
  - sudo make $MAKEFLAGSPARALLEL dist_dir=.
  - cd ..
# FFmpeg
  - sudo apt-get install libavcodec-dev libavformat-dev libswscale-dev libavutil-dev
# SeExpr
  - wget https://github.com/wdas/SeExpr/archive/rel-1.0.1.tar.gz -O /tmp/SeExpr-1.0.1.tar.gz
  - tar zxf /tmp/SeExpr-1.0.1.tar.gz > /dev/null 2>&1
  - cd SeExpr-rel-1.0.1
  - mkdir _build
  - cd _build
  - cmake ..
  - make $MAKEFLAGSPARALLEL && sudo make install
  - cd ../..

  
script:
  - make CONFIG=debug OIIO_HOME=/opt/oiio
